# state.py
"""
Global shared state for the EduMAS pipeline.
This dataclass is passed between all agents to preserve context.
"""
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class EduMASState:
    """
    Global shared state passed between all agents in the pipeline.

    Each agent reads from and writes to this object, ensuring
    no context is lost between agent handoffs.

    Attributes:
        topic: The educational topic requested by the student.
        difficulty: Difficulty level — 'easy', 'medium', or 'hard'.
        student_name: Name of the student being assessed.
        topic_summary: Factual summary fetched by the Coordinator from Wikipedia.
        quiz_questions: List of MCQ dicts generated by the Quiz Generator.
        quiz_file_path: Path to the saved quiz JSON file.
        student_answers: List of student answer choices (e.g. ['A','B','C','A','D']).
        scores: Grading results dict produced by the Grader.
        final_report_path: File path of the report written by the Report Writer.
        pipeline_log: List of log entries capturing each agent's actions.
        error: Any error message encountered during execution.
    """
    topic: str = ""
    difficulty: str = "medium"
    student_name: str = "Student"
    topic_summary: str = ""
    quiz_questions: list[dict] = field(default_factory=list)
    quiz_file_path: str = "output/quiz.json"
    student_answers: list[str] = field(default_factory=list)
    scores: dict = field(default_factory=dict)
    final_report_path: str = ""
    pipeline_log: list[str] = field(default_factory=list)
    error: Optional[str] = None

    def log(self, agent: str, message: str) -> None:
        """Append a structured log entry to the pipeline log."""
        entry = f"[{agent}] {message}"
        self.pipeline_log.append(entry)

    def to_dict(self) -> dict:
        """Serialize the state to a plain dict for JSON export."""
        return {
            "topic": self.topic,
            "difficulty": self.difficulty,
            "student_name": self.student_name,
            "topic_summary": self.topic_summary[:300] + "..." if len(self.topic_summary) > 300 else self.topic_summary,
            "quiz_file_path": self.quiz_file_path,
            "student_answers": self.student_answers,
            "scores": self.scores,
            "final_report_path": self.final_report_path,
            "pipeline_log": self.pipeline_log,
            "error": self.error,
        }
